### ISSUE TITLE
A discrepancy with the behavior of geom_logo in R

### ISSUE THREAD

**Issue by quang-Ivan** [CaoTianze/plotnineseqsuite#1]
The following two code block gives different figures, I believe it's how you deal with seqs contain N cause this.

In R we have 
```R
test_seqs <- c("ATCG", "NNNN", "ATCN", "CGTA")
ggseqlogo(test_seqs,seq_type='dna')
```
And we'll have this figure
![output](https://github.com/user-attachments/assets/056b1ed6-5921-45fb-92f1-475d60dd288d)

In python we have 
```python
test_seqs =["ATCG", "NNNN", "ATCN", "CGTA"]
ggseqlogo(test_seqs, seq_type='DNA')
```
And we'll have this figure with different 4th position logo
![output1](https://github.com/user-attachments/assets/0ae21d9b-0997-40cc-a53d-13495e415428)

**Comment by CaoTianze** [comment]
Hi Qiu:
   It's a bug and I'll fix it as soon as possible. Thanks for pointing out this bug.

**Comment by CaoTianze** [comment]
The bug has been fixed in the latest release. It is already available on PyPI.
